# Generated by Django 5.0.2 on 2024-08-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bungalow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('murQualite', models.CharField(choices=[('Abîmé', 'Abime'), ('Okay', 'Okay'), ('Bon', 'Bon')], default='Bon', max_length=128)),
                ('name', models.CharField(blank=True, max_length=54, null=True)),
            ],
        ),
    ]
