# Generated by Django 5.0.2 on 2024-08-01 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_bungalows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fourniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=54, null=True)),
                ('compte_base', models.IntegerField(blank=True, default=0, null=True)),
                ('attendu', models.IntegerField(blank=True, default=0, null=True)),
                ('bungalow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_bungalows.bungalow')),
            ],
        ),
    ]
